ct_project/urls.py
from django.contrib import admin
from django.urls import include, path
from trials.views import index

urlpatterns = [
    path('', index),   
    path('trials/', include('trials.urls')),
    path('admin/', admin.site.urls),
]

trials/urls.py
from django.urls import path
from . import views

app_name = 'trials'

urlpatterns = [
    path('', views.index, name='index'),    
    path('user_login', views.user_login, name='user_login'),
    path('csv_upload', views.csv_upload, name='csv_upload'),
    path("update/<str:id>", views.trial_update, name="update/id"),
    path("<str:id>", views.get_trial, name="id"),        
    path('register/', views.register, name='register'),
    path('addTrial/', views.addtrial, name='addtrial'),    
    path('logout/', views.user_logout, name='logout'),
    path('ajax/load_cancers/', views.load_cancer_type, name='ajax_load_cancer_type'),
    path('cancerTypes/', views.cancerTypesListView.as_view(), name='cancerTypes'),
    path('cancerTypes/<int:pk>', views.cancerTypesDetailView.as_view(), name="cancerTypesDetails"),
    path('cancerTypes/update/<int:pk>', views.cancerTypesUpdateView.as_view(), name="cancerTypesUpdate"),
    path('cancerTypes/delete/<int:pk>', views.cancerTypesDeleteView.as_view(), name="cancerTypesDelete"),
    path('newTypes/', views.cancerTypesCreateView.as_view(), name='newType'),
    path('triallead/', views.trial_leadListView.as_view(), name='trial_lead'),
    path('triallead/<int:pk>', views.trial_leadDetailView.as_view(), name="trial_leadDetails"),
    path('triallead/update/<int:pk>', views.trial_leadUpdateView.as_view(), name="trial_leadUpdate"),
    path('triallead/delete/<int:pk>', views.trial_leadDeleteView.as_view(), name="trial_leadDelete"),
    path('newlead/', views.trial_leadCreateView.as_view(), name='newlead'),             
]

trials/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.urls import reverse

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)

    # additional classes
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class bodyRegion(models.Model):
    body_region = models.CharField(max_length=200)

    def __str__(self):
        return (f"{self.body_region}")

class cancerTypes(models.Model):    
    cancer_type = models.CharField(max_length=200)
    body_region = models.ForeignKey(bodyRegion, on_delete=models.CASCADE, null=True) 

    class Meta:
        verbose_name = 'cancerType'
        verbose_name_plural = 'cancerTypes'

    def __str__(self):
        return (f"{self.body_region} {self.cancer_type}")

    def get_absolute_url(self):
        return reverse('trials:cancerTypes')

class trial_lead(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    contact = models.CharField(max_length=20)

    def __str__(self):
        return (f"{self.last_name}")

    def get_absolute_url(self):
        return reverse('trials:trial_lead')

class trial(models.Model):    
    name = models.TextField()
    description = models.TextField()
    end_date = models.DateField(null=False)
    inclusion_criteria = models.TextField()
    exclusion_criteria = models.TextField()
    body_region = models.ForeignKey(bodyRegion, on_delete=models.CASCADE)
    cancer_type = models.ForeignKey(cancerTypes, on_delete=models.CASCADE)
    trial_lead = models.ForeignKey(trial_lead, on_delete=models.CASCADE, null=True)    
    Trial_ended = models.BooleanField(default=False)

    def __str__(self):
        return (f"{self.name}")

trials/forms.py
from xml.dom.minidom import Attr
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo, trial, cancerTypes

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        # check fields may want additional info first name and last name
        fields = ('username', 'first_name', 'last_name', 'email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('phone_number',)

class trialForm(forms.ModelForm):
    end_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta():
        model = trial
        fields = '__all__'
       
        widgets = {            
            'name': forms.Textarea(attrs={'class': 'form-control'}),
            'description' : forms.Textarea(attrs={'class': 'form-control'}),
        }

class updateForm(forms.ModelForm):

    class Meta():
        model = trial
        fields = '__all__'


class selectedTrialForm(forms.ModelForm):
    email = forms.EmailField()
    contact = forms.CharField()
    
    class Meta():
        model = trial
        exclude = ('Trial_ended',)

class searchForm(forms.ModelForm):

    class Meta():
        model = trial       
        fields = ('body_region', 'Trial_ended')   

class searchForm1(forms.ModelForm):

    class Meta():
        model = trial       
        fields = ('body_region', 'Trial_ended')
    # overriding the default init method, and setting the queryset of the cancer_type field 
    # to an empty list of cancer types
    # https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['cancer_type'].queryset = cancerTypes.objects.none()

        

trials/views.py
import csv, io
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from trials.forms import UserForm, UserProfileInfoForm, searchForm, trialForm, selectedTrialForm, searchForm1, updateForm
from . import models
from trials.models import cancerTypes, trial, bodyRegion, trial_lead
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)

import datetime

# Create your views here.

def index(request):    
    # check if they have submitted a search
    if request.method == "POST":       
        search_form = searchForm(data=request.POST)               
        if search_form.is_valid():
            # need to check for matches in the database
            if search_form.cleaned_data["Trial_ended"] == False:                
                # todays date variable to only return trials that havent ended
                now = datetime.datetime.now()
                returned_trials = trial.objects.filter(
                    Q(body_region__exact=search_form.cleaned_data["body_region"]) & 
                    # Q(cancer_type__exact=search_form.cleaned_data["cancer_type"]) &
                    Q(end_date__gt = now)).values()                                    
                return render(request,'trials/searchresults.html',
                                {'trials':returned_trials
                                })
            else:
                returned_trials = trial.objects.filter(
                    Q(body_region__exact=search_form.cleaned_data["body_region"]))                      
                return render(request,'trials/searchresults.html',
                                {'trials':returned_trials
                                })
        else:
            #if form not valid print out errors to terminal update for prod app
            print(search_form.errors)
            return render(request,"trials/error.html",{
            "msg": "form not valid"
            }) 
            
    else:
        # view for dependent cancer typ drop down box only
        search_form = searchForm1()
        return render(request,'trials/index.html',
                                {'search_form':search_form
                                })

@login_required
def user_logout(request):
    logout(request)    
    return HttpResponseRedirect(reverse('trials:index'))

#Create View - decorator so needs to be logged in
@login_required
def addtrial(request):
    # check if form is being requested or has been completed. 
    if request.method == "POST":
        trial_form = trialForm(data=request.POST)
        #checks submitted form is valid and if is saves to database
        if trial_form.is_valid():
            trial_form.save()
            return HttpResponseRedirect(reverse('trials:index'))
        else:
            #if form not valid print out errors to terminal update for prod app
            print(trial_form.errors)
    # if first vist return form
    else:
        trial_form = trialForm()
        return render(request, 'trials/addtrial.html',
                                {'trial_form':trial_form
                                })

def register(request):
    # used to check if user is registered
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user =user_form.save()
            user.set_password(user.password)
            user.save()
            # add additional information phone number
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True            
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'trials/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered': registered})

def user_login(request):
    # need to update so it doesn't errorif the wrong details are entered
    if request.method == 'POST':
        # username and password in bracket relates to 'names' username and password specified in login.html
        username = request.POST.get('username')
        password = request.POST.get('password')

        # user Django builting authentication method
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('trials:index'))
            else:
                return HttpResponse("Account not activer")
        else:
            print("Someone tried to login and failed")
            print(f"Username: {username} and password {password}")
            return HttpResponse("Invalid Logn Details")
    else:
        return render(request, 'trials/login.html')

# Read View
def get_trial(request,id):
    '''
        Get page for selected trial
        1. get full trial deails        2. 
        3. if content not found, redirect to error page
    '''    
    try:
        trialSelected = trial.objects.get(id=id)
    except:
        return redirect('trials:index') 
    
       
    if trialSelected is None:
    # no trial found 
        return render(request,"trials/error.html",{
            "msg": "no trial of that name"
        }) 
    else:        
    # trial found
    # issue with end date due to form how do we get drop down but over write when completed?
    # to access trialSelected.trial_lead is foreign key other firld in foreign modle access by.field names
    #e.g. trialSelected.trial_lead.email and trialSelected.trial_lead.contact below
        data = {
            'name': trialSelected.name,
            'description': trialSelected.description,
            'end_date': trialSelected.end_date,
            'inclusion_criteria': trialSelected.inclusion_criteria,
            'exclusion_criteria': trialSelected.exclusion_criteria,
            'body_region': trialSelected.body_region,
            'cancer_type': trialSelected.cancer_type,
            'trial_lead': trialSelected.trial_lead,
            'email': trialSelected.trial_lead.email,
            'contact': trialSelected.trial_lead.contact
        }
        trial_form = selectedTrialForm(initial=data)           
    
        return render(request,"trials/trialpage.html",{                
                "trial_form":trial_form,
                "trialSelected":trialSelected       
            })

def load_cancer_type(request):
    body_region = request.GET.get('body_region')
    cancer_type = cancerTypes.objects.filter(body_region=body_region).order_by('cancer_type') 
    return render(request, 'trials/cancer_dropdown_list_options.html', {'cancer_type': cancer_type})

# Update View - decorator so needs to be logged in
@login_required
def trial_update(request, id):    
    if request.method == 'POST':
        # need to get the trial to update rather than create
        selected = trial.objects.get(id=id)
        # creates an the update of the instance called.
        update_form = updateForm(request.POST, instance=selected)
        if update_form.is_valid():            
            update_form.save() 
            # search form to create new index page when redirected.
            search_form = searchForm1()          
            return render(request,'trials/index.html',
                                {'search_form':search_form,
                                 "msg": "Trial Saved"
                                })           
        else:
            return render(request,"trials/error.html",{
            "msg": update_form.errors
            })
    else:
        return redirect('index')

@login_required
def csv_upload(request):
    template = "trials/trial_upload.html"
    prompt = {
        'order': 'Order of CSV should be name, description, end_date (YYYY-MM-DD), inclusion_criteria, exclusion_criteria, body_region, cancer_type, trial_lead, use "" to enclose fields containing commas'
    }

    if request.method == "POST":
        csv_file = request.FILES['file']
        # check the file is a CSV
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'This is not a csv File')
        else:
            data_set = csv_file.read().decode('UTF-8')
            io_string = io.StringIO(data_set)
            # skip first line as usually a header
            next(io_string)
            print(f'the io_string: {io_string.read()}')            
            for column in csv.reader(io_string, delimiter=',', quotechar='"'):
                _, created = trial.objects.update_or_create(
                    name=column[0],
                    description=column[1],
                    end_date=column[2], 
                    inclusion_criteria=column[3], 
                    exclusion_criteria=column[4], 
                    body_region=bodyRegion.objects.get(body_region = column[5]), 
                    cancer_type=cancerTypes.objects.get(cancer_type = column[6]), 
                    trial_lead=trial_lead.objects.get(last_name = column[7]),                    
                )
        context = {}
        return render(request,template, context)
    else:
        return render(request, template, prompt)

class cancerTypesListView(ListView):
    # If you don't pass in this attribute,

templates/trials/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Cancer Trials</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-light navbar-static-top" style="background-color: darkblue;">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'trials:index' %}">Search Page</a></li>           

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'trials:addtrial' %}">New Trial</a></li>
          <li><a class="navbar-link" href="{% url 'trials:trial_lead' %}">Trial Leads</a></li>
          <li><a class="navbar-link" href="{% url 'trials:cancerTypes' %}">Cancer Types</a></li>                   
          <li><a class="navbar-link" href="{% url 'trials:logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'trials:user_login' %}">Trial Administration</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">



    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>   
  </body>
  <footer>
    <div class="alert alert-warning text-center">
      <P>This is a proof of concept system.</P>
      <P>No data held in this system relates to actual Cancer Trails </P>
    </div>    
  </footer>
</html>

templates/trials/cancer_dropdown_list_options.html
<!-- used to lookup depenednent cancer type field only -->
<option value="">---------</option>
{% for cancer in cancer_type %}
<option value="{{ cancer.id }}">{{ cancer }}</option>
{% endfor %}

templates/trials/cancertype_detail.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
    <div class="jumbotron">
        <p>Id: {{cancertype_details.id}}</p>
        <p>Body Area: {{cancertype_details.body_region}}</p>
        <p>Cancer Type: {{cancertype_details.cancer_type}}</p>            
      </div>
      <div class="container">
        <p><a class='btn btn-warning' href="{% url 'trials:cancerTypesUpdate' pk=cancertype_details.id %}">Update</a>  <a class='btn btn-warning' href="{% url 'trials:cancerTypesDelete' pk=cancertype_details.id %}">Delete</a></p>    
      </div>

    {% endblock %}

templates/trials/cancertypes_confirm_delete.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
        <h1>Delete {{cancertype.body_region}} - {{cancertype.cancer_type}}?</h1>

            <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'trials:cancerTypes' %} ">Cancel</a>

            </form>
    {% endblock %}

templates/trials/cancertypes_list.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
    <div class="container">
        <p><a class='btn btn-warning' href="{% url 'trials:newType' %}">Add New Type</a></p>    
    </div>

        {% for cancer in cancerTypes_list %}
            <h2><li>{{cancer.body_region}} - <a href="{{cancer.id}}">{{cancer.cancer_type}} </a></li></h2>
        {% endfor %}

    {% endblock %}

templates/trials/error.html
<!DOCTYPE html>
{% extends "trials/base.html" %}

{% block body %}

<h1 class="text-danger display-1"> Error 404 : {{msg}} </h1>
{% endblock %}

templates/trials/index.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block%}

    <h1>Cancer Trials Home Page</h1>

    <h1>{{msg}}</h1>
    
    <div class="jumbotron">
        <h2>Please select a Body Region to see current trials</h2>
        <form action="{% url 'trials:index' %}" method="post" id="searchForm" data-cancerTypes-url="{% url 'trials:ajax_load_cancer_type' %}" >
            {% csrf_token %}
            <!-- {{ search_form.as_p}} -->
            <div class="form-group">
              <label for="body_region">Body Region</label>
              {{ search_form.body_region }}
            </div>            
            {% if user.is_authenticated %}
            <div class="form-check">              
              {{ search_form.Trial_ended }}
              <label class="form-check-label" for="Trial_ended">Include Ended Trials </label>
            </div>              
            {% endif %}
            <input type="submit" class="btn btn-primary btn-lg " name="" value="Search">     
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $("#id_body_region").change(function () {
        var url = $("#searchForm").attr("data-cancerTypes-url");  // get the url of the `load_cancer_types` view
        var body_regionId = $(this).val();  // get the selected body_region ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'body_region': body_regionId       // add the body_region id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cancer_types` view function
            $("#id_cancer_type").html(data);  // replace the contents of the cancer input with the data that came from the server
          }
        });

      });
    </script>

   
    {% endblock %}

templates/trials/searchresults.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block%}   
    <table class="table">
        <tr>
            <th>Description</th>  
            <th>Description</th>          
            <th>End Date</th>
        </tr>         
        {% for trialName in trials %}        
        <tr>
            <td>
                <a href= "{% url 'trials:id' id=trialName.id %}">{{ trialName.name }}</a>
            </td>
            <td>
                {{ trialName.description }}
            </td>
            <td>
                {{ trialName.end_date }}
            </td>
        </tr>                                 
        {% empty %}
            <h2>No Trials meet that criteria</h2>
        {% endfor %}
    </table>
    
       
               

    {% endblock %}

templates/trials/trial_lead_confirm_delete.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
        <h1>Delete {{trial_lead.first_name}} - {{trial_lead.last_name}}?</h1>

            <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'trials:trial_lead' %} ">Cancel</a>

            </form>
    {% endblock %}

templates/trials/trial_lead_detail.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
    <div class="jumbotron">
        <p>Id: {{trial_lead_details.id}}</p>
        <p>First Name: {{trial_lead_details.first_name}}</p>
        <p>Surname: {{trial_lead_details.last_name}}</p>
        <p>Email Address: {{trial_lead_details.email}}</p>
        <p>Telephone Number: {{trial_lead_details.contact}}</p>            
      </div>
      <div class="container">
        <p><a class='btn btn-warning' href="{% url 'trials:trial_leadUpdate' pk=trial_lead_details.id %}">Update</a>  <a class='btn btn-warning' href="{% url 'trials:trial_leadDelete' pk=trial_lead_details.id %}">Delete</a></p>    
      </div>

    {% endblock %}

templates/trials/trial_lead_form.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
    
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class='btn btn-primary' value="Submit">
      
        </form>
        
    {% endblock %}

templates/trials/trial_lead_list.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block %}
    <div class="container">
        <p><a class='btn btn-warning' href="{% url 'trials:newlead' %}">Add New Trial Lead</a></p>    
    </div>

        {% for lead in trial_lead_list %}
            <h2><li>{{lead.first_name}} - <a href="{{lead.id}}">{{lead.last_name}} </a></li></h2>
        {% endfor %}

    {% endblock %}

templates/trials/trial_upload.html
<!DOCTYPE html>
{% extends "trials/base.html" %}
    {% block body_block%}

        {% if messages %}
            {% for message in messages %}
                <div>
                    <strong>{{message|safe}}</strong>
                </div>
            {% endfor %}
        {% else %}
            <div class="jumbotron">
                {{order}}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>Upload a file</label>
                    <input type="file" name="file">
                    <p>File must be a CSV</p>
                    <button type="submit">Upload</button>
                </form>
            </div>
        {% endif %}


    {% endblock %}

templates/trials/trialpage.html
<!DOCTYPE html>
{% extends "trials/base.html" %}

{% block body_block %}    

    <div class="jumbotron">
        <!-- to do need to redirect to a view to save the update -->
        {% if user.is_authenticated %}
            <form action="{% url 'trials:update/id' id=trialSelected.id %}" id="updateForm" method="post">
                <div class="form-group">
                    {% csrf_token %}
                    {{ trial_form}}
                </div>            
            <input type="submit" name="" value="trial_update">
        {% else %}
            <figure class="text-center">
                <H3  class="display-3"><u>{{ trialSelected.name }}</u></H3>
            </figure>
            <table class="table table-bordered">
                <tr>
                    <th>Description</th>
                    <td>{{ trialSelected.description }}</td>
                </tr>
                <tr>
                    <th>Trial End Date</th>
                    <td>{{ trialSelected.end_date }}</td>
                </tr>
                <tr>
                    <th>Trial Inclusion Criteria</th>
                    <td>{{ trialSelected.inclusion_criteria }}</td>
                </tr>
                <tr>
                    <th>Trial Exclusion Criteria</th>
                    <td>{{ trialSelected.exclusion_criteria }}</td>
                </tr>                
                <tr>
                    <th>Cancer Type</th>
                    <td>{{ trialSelected.cancer_type }}</td>
                </tr>
                <tr>
                    <th>Trial Contact</th>
                    <td>{{ trialSelected.trial_lead.first_name }} {{ trialSelected.trial_lead.last_name  }}</td>
                </tr>
                <tr>
                    <th>Contact Email</th>
                    <td>{{ trialSelected.trial_lead.email }}</td>
                </tr>
                <tr>
                    <th>Contact Phone Number</th>
                    <td>{{ trialSelected.trial_lead.contact }}</td>
                </tr>
            </table>                          
        {% endif %}
             
    
        </form>
    </div>  

{% endblock %}